name: Scrape Data, build and upload Model

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 

      - name: setup python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.12.1' 
          cache: 'pip'

      - name: install python packages
        run: pip install -q -r requirements.txt

      - name: scrape Wiki and load the Data
        working-directory: ./Scraper
        run: |
          python scraper.py \
            -u "${{ secrets.MONGO_URI }}" 
            

      - name: create Model and Upload
        working-directory: ./models
        run: |
          python createModel.py \
            -u "${{ secrets.MONGO_URI }}" \
            -c "${{ secrets.STORAGE }}"